version: "3"

services:
  data-science:
    build: ./data-science
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
      - ./data:/home/jovyan/work/data

  demo-api:
    build: ./demo-api
    ports:
      - 80:80

# mlflow
# mlops-demo-api