version: "3"

services:
  data-science:
    build: ./data-science
    ports:
      - "8888:8888"
    volumes:
      - ./data-science:/home/jovyan/data-science

  demo-api:
    build: ./demo-api
    ports:
      - 80:80

# mlflow
# mlops-demo-api